#Background
This notebook is meant to turn Raw data from Field Day Lab's game, Lakeland, into data capable of being analyzed using methods of Quantitative Ethnography such as Epistemic Network Analysis.

# Read in Everything

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
import pandas as pd
from matplotlib import pyplot as plt
from math import ceil
import numpy as np
pd.options.display.max_columns = 1000
from google.colab import files
import urllib.request
from zipfile import ZipFile
from io import BytesIO

In [ ]:
# !ls "/content/drive"
import os
ENA_folder = '/content/drive/My Drive/Research/2021_JLA_GameDataQE/Data'
data_fpath = lambda fname: os.path.join(ENA_folder, fname)
ENA_path = "Lakeland_2019Nov.tsv"
Proc_path = "Lakeland60.csv"
# ENA_path = "/content/drive/My Drive/Lakeland_ENA/Raw_Lakeland_2019Dec.csv"

# Establish Data Frame

In [ ]:
!curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=11JjtaQrO9gqM3ndGgcW4ZQRfTph_W8Wt" > /dev/null
!curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=`awk '/download/ {print $NF}' ./cookie`&id=11JjtaQrO9gqM3ndGgcW4ZQRfTph_W8Wt" -o "LAKELAND_2019Nov.csv"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408    0   408    0     0   3642      0 --:--:-- --:--:-- --:--:--  3610
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1932M    0 1932M    0     0   144M      0 --:--:--  0:00:13 --:--:-- 38.5M

In [ ]:
!ls -l LAKELAND_2019Nov.csv

-rw-r--r-- 1 root root 2026269129 Aug 22 02:55 LAKELAND_2019Nov.csv

In [ ]:
#Read in CSV (raw)
df_Raw = pd.read_csv("LAKELAND_2019Nov.csv", sep='\t')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
df_Raw.shape

(1479904, 19)

In [ ]:
#Filter Raw Dataframe
df = df_Raw.dropna(subset = ['player_id'])

In [ ]:
df.shape

(123630, 19)

In [ ]:
df.head()

,id,app_id,app_id_fast,app_version,session_id,persistent_session_id,player_id,level,event,event_custom,event_data_simple,event_data_complex,client_time,client_time_ms,server_time,remote_addr,req_id,session_n,http_user_agent,tile_states,tile_nutritions,continue,language,audio,fullscreen,event_category,event_label,event_type,blurb_history,tile,marks,buy,cost,curr_money,success,tiles,farmbits,items,money,speed,achievements,num_checkpoints_completed,raining,curr_selection_type,curr_selection_data,camera_center,gametime,timestamp,num_food_produced,num_poop_produced,num_milk_produced,buy_hovers,farmbit,achievement,emote_enum,item,cur_speed,prev_speed,manual,prev_mark,shop_open,to_state,selected_buy,grave,achievements_open,road_builds
150197,51254882,LAKELAND,LAKELAND,15,19100107575255310,19100107575255310,a017,1,CUSTOM,1,0,"{""tile_states"": [3, 3, 3, 3, 3, 3, 3, 3, 3, 4,...",2019-11-25 13:59:23,499,2019-11-25 07:59:23,None,19100107592318700,0,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,"[3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 5, 3, ...","[0, 0, 1, 1, 12, 12, 12, 12, 12, 12, 12, 12, 1...",0,"""english""",1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150198,51255081,LAKELAND,LAKELAND,15,19100107575255310,19100107575255310,a017,1,CUSTOM,2,0,"{""event_category"": ""begin"", ""event_label"": ""bu...",1574690374141,142,2019-11-25 07:59:34,None,19100107593498740,1,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,"""begin""","""build_a_house""","""tutorial""",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150199,51255304,LAKELAND,LAKELAND,15,19100107575255310,19100107575255310,a017,1,CUSTOM,3,0,"{""tile"": [0, 12, 1, 1, 25, 19], ""marks"": [1, 1...",2019-11-25 13:59:43,179,2019-11-25 07:59:44,None,19100107594375784,2,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 12, 1, 1, 25, 19]","[1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150200,51255434,LAKELAND,LAKELAND,15,19100107575255310,19100107575255310,a017,1,CUSTOM,3,0,"{""tile"": [0, 8, 6, 6, 23, 25], ""marks"": [1, 1,...",2019-11-25 13:59:49,283,2019-11-25 07:59:50,None,19100107594980116,3,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 8, 6, 6, 23, 25]","[1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150201,51255498,LAKELAND,LAKELAND,15,19100107575255310,19100107575255310,a017,1,CUSTOM,3,0,"{""tile"": [0, 12, 1, 1, 21, 19], ""marks"": [1, 1...",2019-11-25 13:59:52,708,2019-11-25 07:59:52,None,19100107595287100,4,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 12, 1, 1, 21, 19]","[1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Get names of indexes for which column event_cutom is 0, 2, ...
indexNames = (df[df["event_custom"] == 0].index)

# Delete these row indexes from dataFrame
df = df.drop(indexNames)

In [ ]:
df.shape

(120025, 66)

In [ ]:
import json

for index,row in df.iterrows():
      tmp = json.loads(row["event_data_complex"])
      for key in tmp.keys():
            df.loc[index, key] = json.dumps(tmp[key])
#            df[row[key]] = tmp[key]

In [ ]:
df.tail()

,id,app_id,app_id_fast,app_version,session_id,persistent_session_id,player_id,level,event,event_custom,event_data_simple,event_data_complex,client_time,client_time_ms,server_time,remote_addr,req_id,session_n,http_user_agent,tile_states,tile_nutritions,continue,language,audio,fullscreen,event_category,event_label,event_type,blurb_history,tile,marks,buy,cost,curr_money,success,tiles,farmbits,items,money,speed,achievements,num_checkpoints_completed,raining,curr_selection_type,curr_selection_data,camera_center,gametime,timestamp,num_food_produced,num_poop_produced,num_milk_produced,buy_hovers,farmbit,achievement,emote_enum,item,cur_speed,prev_speed,manual,prev_mark,shop_open,to_state,selected_buy,grave,achievements_open,road_builds
1231560,63185729,LAKELAND,LAKELAND,15,19100522470362350,19100107580418784,a004,1,CUSTOM,24,0,"{""farmbit"": [20, 21, 0, 2, 1, 215, 203, 254, 2...",2019-12-11 21:42:57,90,2019-12-11 15:42:58,None,19110315425738170,996,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[20, 21, 0, 2, 1, 215, 203, 254, 26]",NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1231561,63185809,LAKELAND,LAKELAND,15,19100522470362350,19100107580418784,a004,1,CUSTOM,24,0,"{""farmbit"": [22, 25, 7, 2, 4, 195, 100, 114, 1...",2019-12-11 21:43:23,141,2019-12-11 15:43:24,None,19110315432350704,997,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[22, 25, 7, 2, 4, 195, 100, 114, 15]",NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1231562,63185814,LAKELAND,LAKELAND,15,19100522470362350,19100107580418784,a004,1,CUSTOM,24,0,"{""farmbit"": [22, 22, 7, 3, 4, 193, 98, 253, 13...",2019-12-11 21:43:24,618,2019-12-11 15:43:25,None,19110315432490216,998,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[22, 22, 7, 3, 4, 193, 98, 253, 13]",NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1231563,63185822,LAKELAND,LAKELAND,15,19100522470362350,19100107580418784,a004,1,CUSTOM,16,0,"{""cur_speed"": 1, ""prev_speed"": 2, ""manual"": 1,...",2019-12-11 21:43:27,416,2019-12-11 15:43:28,None,19110315432775064,999,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1231564,63868758,LAKELAND,LAKELAND,15,19100522470362350,19100107580418784,a004,1,CUSTOM,13,0,"{""shop_open"": true, ""event_custom"": 13}",2019-12-12 18:45:10,4,2019-12-12 12:45:12,None,19110412451075656,1000,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,true,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Drop Columns
df = df.drop(columns=['id', 'app_id', 'app_id_fast', 'persistent_session_id', 'app_version', 'event','language','money','speed','achievements', 'event_data_simple', 'tiles', 'farmbits', 'items', 'num_checkpoints_completed','curr_selection_data', 'camera_center', 'num_food_produced', 'num_poop_produced', 'camera_center', 'num_milk_produced','client_time_ms', 'server_time', 'remote_addr'])

In [ ]:
#Data Amount
count_row = df.shape[0]
count_col = df.shape[1]
print(count_col,count_row)

43 120025

#Assign Metadata

In [ ]:
#This snippet is for testing the progress and convo columns and redoing them
#df = df.drop(axis=1, columns=['progress','convo'])

In [ ]:
#Progress Column
#Assign 1 at start for each session_ID, customevent == 0
#Assign 2 after fertilizer tutorial customevent == 2, event_category == 5
#Assign 3 after event custom==2, event_category == 7
#Assign 4 after event custom == 2, event_category == 20

currentSessionValueDict = { }
for index,row in df.iterrows():
  sessionId = row['session_id']
  if ((not sessionId in currentSessionValueDict) or
      (row['event_custom'] == 1)
  ):
    currentSessionValueDict[sessionId] = 1

  progress = currentSessionValueDict[sessionId]
  if ((row['event_custom'] == 2 and row['event_category'] == 'begin' and row['event_label'] == 'buy_fertilizer') or
      (row['event_custom'] == 2 and row['event_category'] == 'begin' and row['event_label'] == 'buy_livestock') or
      (row['event_custom'] == 2 and row['event_category'] == 'begin' and row['event_label'] == 'rain')
  ):
    progress = progress + 1
    currentSessionValueDict[sessionId] = progress;
  
  df.loc[index, 'progress'] = progress

df['progress'].unique()

array([1.])

In [ ]:
#Conversation Column
#Sessions with same Session ID = Same conversation until "Continue" then 2 until continue/startgame then 3
#Session = 1 when startgame and no continue, increment any time start game w/ continue

currentSessionConvoDict = { }
for index,row in df.iterrows():
  sessionId = row['session_id']
  if ((not sessionId in currentSessionConvoDict) or
      (row['event_custom'] == 1 and row['continue'] == '0')
  ):
    currentSessionConvoDict[sessionId] = 1

  convo = currentSessionConvoDict[sessionId]
  if (row['event_custom'] == 1 and row['continue'] == '1'):
    convo = convo + 1
    currentSessionConvoDict[sessionId] = convo;
  
  df.loc[index, 'convo'] = convo 

df['convo'].unique()

array([1.])

In [ ]:
#Games Played
# Starts at 1 and goes up by one for each event_custom=0 event.

currentSessionValueDict = { }
for index,row in df.iterrows():
  sessionId = row['session_id']
  if ((not sessionId in currentSessionValueDict)):
    currentSessionValueDict[sessionId] = 0

  value = currentSessionValueDict[sessionId]
  if (row['event_custom'] == 1 and row['continue'] == '0'):
    value = value + 1
    currentSessionValueDict[sessionId] = value;
  
  if(value < 1):
    value = 1

  df.loc[index, 'games_played'] = value 

df['games_played'].unique()

array([1.])

In [ ]:
#Speaker Column
#Assign Game to events 

playr = [3,4,5,6,7,8,9,10,11,12,13,14,15,16,30]

def f(row):
    if row['event_custom'] in playr :
        val = 'player'
    else:
        val = 'game'
    return val


df['speaker'] = df.apply(f, axis=1)

# Convert Data - Events and Descriptors
0. gamestate - not used
2. startgame - X
3. checkpoint - Tutorial
4. selecttile
4. selectfarmbit
1. selectitem
1. selectbuy
1. buy
1. cancelbuy
1. roadbuilds
1. tileuseselect
1. itemuseselect
1. togglenutrition
1. toggleshop
1. toggleachievements
1. skiptutorial
1. speed
1. achievement
1. farmbitdeath
1. blurb (Not implemented)
1. click (Not implemented)
1. rainstopped
1. history
1. endgame
1. emote
1. farmfail
1. bloom
1. farmharvested
1. milkproduced
1. poopproduced
1. debug
1. newfarmbit

In [ ]:
#Event Number to Words
mapping = {
    0:'gamestate', 1:'startgame:You set out to form a new town called Lakeland. Your people love to play in the water. Grow your town without destroying their lakes.', 2:'checkpoint', 3:'selecttile', 4:'selectfarmbit', 5:'selectitem', 6:'selectbuy', 7:'buy', 8:'cancelbuy', 9:'roadbuilds', 10:'tileuseselect', 11:'itemuseselect', 12:'togglenutrition', 13:'toggleshop', 14:'toggleachievements', 15:'skiptutorial', 16:'speed', 17:'achievement', 18:'farmbitdeath', 19:'blurb', 20:'click', 21:'rainstopped', 22:'history', 23:'endgame', 24:'emote', 25:'farmfail', 26:'bloom', 27:'farmharvested', 28:'milkproduced', 29:'poopproduced', 30:'debug', 31:'newfarmbit'}
df = df.replace({'event_custom': mapping})

In [ ]:
#Menu Toggles To Meaning
mapping = {'True':'Player Opened', 'False':'Player Closed', '0':'Player Closed'}
df = df.replace({'achievements_open':mapping})
df= df.replace({'shop_open':mapping})

nutr_mapping = {'False': 'Player Turned Off', 'True':'Player Turned On'}
df = df.replace({'to_state':nutr_mapping})

In [ ]:
#Emojis to Words - 24
mapping_emoji = {'0':'null', '1':'Im hungry', '2':'i need food', '3':'i need a nap!', '4':'i want to play in the water', '5':'im so sad', '6':'Im sick Puke Emoji', '7':'Yumface', '8':'Im tired sleepy face', '9':'Im happy happy face', '10':'Ive got my floatie on flamingo swim emoji', '11':'Off to market sale'}
mapping_emoji
df = df.replace({'emote_enum': mapping_emoji})

In [ ]:
#Speed Data - 16
#cur_speed
mapping_speed = {'0':'null', '1':'pause', '2':'play x 1', '3':'fast x 4', '4':'fast x 16',}
mapping_speed
df = df.replace({'cur_speed': mapping_speed})
#Prev_speed
df = df.replace({'prev_speed': mapping_speed})
#Manual
mapping_manual = {'0':'null', '1':'Changed by Player'}
mapping_manual
df = df.replace({'manual': mapping_manual})

In [ ]:
#Achievement Data - 17
mapping_achievement = {'0':'exist get a visitor', '1':'group 3 workers', '2':'town a small community', '3':	'city 10 townmembers', '4':'farmer own a farm!', '5':'farmers get three farms', '6':	'farm town 5 farms!', '7': 'mega farm 10 farm industry', '8':	'paycheck $500', '9':	'thousandair $1000','10':	'stability $5000','11':	'riches $10000', '12':	'bloom algae destroys one tile','13':	'big bloom algae spreads to 3 tiles','14':	'huge bloom you have an algae problem','15':	'massive bloom a whole lake destroyed'}
df = df.replace({'achievement': mapping_achievement})

In [ ]:
#Buy
buy_type_to_enum = {"null": 0,
    "home": '1',
    "food": '2',
    "farm": '3',
    "fertilizer": '4',
    "livestock": '5',
    "skimmer": '6',
    "sign": '7',
    "road": '8'}
buy_enum_to_type = {v:k for k,v in buy_type_to_enum.items()}

df = df.replace({'buy': buy_enum_to_type})

In [ ]:
#Success
succ_desc={
    'True':"I can buy this.",
    'False' : "I can't buy this.",
    1: "I bought it!",
    2: "I can't put that there..."}

df = df.replace({'success':succ_desc})

In [ ]:
#prev_mark
mark_type_to_enum = {'null': 0,
    "use": 1,
    "sell": 2,
    "feed": 3}
mark_enum_to_type = {v:k for k,v in mark_type_to_enum.items()}

df=df.replace({'prev_mark':mark_enum_to_type})

In [ ]:
df.head(n=20)

,session_id,player_id,level,event_custom,event_data_complex,client_time,req_id,session_n,http_user_agent,tile_states,tile_nutritions,continue,audio,fullscreen,event_category,event_label,event_type,blurb_history,tile,marks,buy,cost,curr_money,success,raining,curr_selection_type,gametime,timestamp,buy_hovers,farmbit,achievement,emote_enum,item,cur_speed,prev_speed,manual,prev_mark,shop_open,to_state,selected_buy,grave,achievements_open,road_builds,progress,convo,games_played,speaker
150197,19100107575255310,a017,1,1,"{""tile_states"": [3, 3, 3, 3, 3, 3, 3, 3, 3, 4,...",2019-11-25 13:59:23,19100107592318700,0,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,"[3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 5, 3, ...","[0, 0, 1, 1, 12, 12, 12, 12, 12, 12, 12, 12, 1...",0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150198,19100107575255310,a017,1,2,"{""event_category"": ""begin"", ""event_label"": ""bu...",1574690374141,19100107593498740,1,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,"""begin""","""build_a_house""","""tutorial""",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150199,19100107575255310,a017,1,3,"{""tile"": [0, 12, 1, 1, 25, 19], ""marks"": [1, 1...",2019-11-25 13:59:43,19100107594375784,2,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 12, 1, 1, 25, 19]","[1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150200,19100107575255310,a017,1,3,"{""tile"": [0, 8, 6, 6, 23, 25], ""marks"": [1, 1,...",2019-11-25 13:59:49,19100107594980116,3,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 8, 6, 6, 23, 25]","[1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150201,19100107575255310,a017,1,3,"{""tile"": [0, 12, 1, 1, 21, 19], ""marks"": [1, 1...",2019-11-25 13:59:52,19100107595287100,4,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 12, 1, 1, 21, 19]","[1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150202,19100107575255310,a017,1,6,"{""buy"": 1, ""cost"": 1000, ""curr_money"": 1000, ""...",2019-11-25 13:59:54,19100107595419884,5,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,home,1000,1000,true,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150203,19100107575255310,a017,1,0,"{""tiles"": ""0,0,6,6,0,0,5,5,0,1,5,5,0,2,6,6,0,1...",2019-11-25 14:00:02,19100108000291816,6,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3,1679,1574690402376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150204,19100107575255310,a017,1,7,"{""client_time"": 1574690402376, ""buy"": 1, ""tile...",1574690402376,19100108000776296,7,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 12, 1, 1, 21, 25]",NaN,home,NaN,NaN,true,NaN,NaN,NaN,NaN,"[[0, 13, 1, 1, 17, 24, 1, -4200], [0, 12, 1, 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150205,19100107575255310,a017,1,3,"{""tile"": [0, 12, 1, 8, 21, 25], ""marks"": [1, 1...",2019-11-25 14:00:02,19100108000776296,8,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 12, 1, 8, 21, 25]","[1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150206,19100107575255310,a017,1,31,"{""farmbit"": [21, 25, 13, 3, 1, 255, 255, 255, ...",2019-11-25 14:00:07,19100108000776296,9,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[21, 25, 13, 3, 1, 255, 255, 255, 102]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150207,19100107575255310,a017,1,4,"{""farmbit"": [21, 25, 13, 3, 1, 254, 254, 254, ...",2019-11-25 14:00:07,19100108002053944,10,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[21, 25, 13, 3, 1, 254, 254, 254, 101]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150208,19100107575255310,a017,1,3,"{""tile"": [0, 12, 1, 8, 21, 25], ""marks"": [1, 1...",2019-11-25 14:00:20,19100108002053944,11,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 12, 1, 8, 21, 25]","[1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150209,19100107575255310,a017,1,3,"{""tile"": [0, 12, 2, 2, 18, 17], ""marks"": [1, 1...",2019-11-25 14:00:23,19100108002300652,12,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 12, 2, 2, 18, 17]","[1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150210,19100107575255310,a017,1,2,"{""event_category"": ""end"", ""event_label"": ""buil...",1574690426787,19100108002689948,13,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,"""end""","""build_a_house""","""tutorial""","[-50874, -48597, -47398, -31921, -24397, -2011...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150211,19100107575255310,a017,1,17,"{""achievement"": 0, ""event_custom"": 17}",2019-11-25 14:00:26,19100108003109890,14,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,exist get a visitor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150212,19100107575255310,a017,1,4,"{""farmbit"": [30, 30, 13, 3, 1, 228, 218, 218, ...",2019-11-25 14:00:31,19100108003109890,15,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[30, 30, 13, 3, 1, 228, 218, 218, 65]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150213,19100107575255310,a017,1,3,"{""tile"": [0, 12, 1, 1, 27, 24], ""marks"": [1, 1...",2019-11-25 14:00:35,19100108003536344,16,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 12, 1, 1, 27, 24]","[1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150214,19100107575255310,a017,1,3,"{""tile"": [0, 12, 1, 8, 21, 25], ""marks"": [1, 1...",2019-11-25 14:00:39,19100108003995704,17,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[0, 12, 1, 8, 21, 25]","[1, 1, 1, 1]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150215,19100107575255310,a017,1,2,"{""event_category"": ""begin"", ""event_label"": ""bu...",1574690443447,19100108004397396,18,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,"""begin""","""buy_food""","""tutorial""",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
150216,19100107575255310,a017,1,24,"{""farmbit"": [23, 26, 13, 2, 1, 201, 179, 179, ...",2019-11-25 14:00:57,19100108005757390,19,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[23, 26, 13, 2, 1, 201, 179, 179, 26]",NaN,Ive got my floatie on flamingo swim emoji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game

#JSON Manipulation


*   Tile
*   Items
* Farmbits

In [ ]:
#Check variation of nutrition

import json

def stats(dataSequence):
    return {
        'max': dataSequence.max(),
        'min': dataSequence.min(),
        'median': dataSequence.median(),
        'mean': dataSequence.mean(),
        'mode': dataSequence.mode(),
        'std':dataSequence.std()
    }


# Gets all the data that is not 'None' in a column
def getActualColumnData(columnLabel):
    return df[df[columnLabel] != 'None'][columnLabel]

def json2obj(x):
    return json.loads(x) if (x!=None and x!='None') else None

# Creates a lambda for mapping a dataFrame column from one value to another
def applyMapping(mapping):
    return lambda x: mapping[x] if (x!=None and x!='None') else None

# Creates a lambda for mapping a dataFrame column from an array of values to a 
# value from specified position in the array
def applyArrayPos(position):
    return lambda x: x[position-1] if (isinstance(x,list) and len(x)>=position) else None


def getData(dataConfig):
    column = getActualColumnData(dataConfig['columnLabel'])
    if(dataConfig['arrayPosition'] != None):
        column = column.map(json2obj).map(applyArrayPos(dataConfig['arrayPosition']))
    if(dataConfig['mapping'] != None):
        column = column.map(applyMapping(dataConfig['mapping']))
    return column

nutritionConfig = {
    'name' : 'nutrition',
    'columnLabel': 'tile',
    'arrayPosition': None,
    'mapping': None,
}

nutritionData = getData(nutritionConfig)

nutritionData

150197                       NaN
150198                       NaN
150199     [0, 12, 1, 1, 25, 19]
150200      [0, 8, 6, 6, 23, 25]
150201     [0, 12, 1, 1, 21, 19]
                   ...
1231560                      NaN
1231561                      NaN
1231562                      NaN
1231563                      NaN
1231564                      NaN
Name: tile, Length: 120025, dtype: object

In [ ]:
#Tile Type Change
import math

#tile_type to enum conversion
tile_type_to_enum = {
    "null": 0,
    "land": 1,
    "rock": 2,
    "grave": 3,
    "sign": 4,
    "lake": 5,
    "shore": 6,
    "forest": 7,
    "home": 8,
    "farm": 9,
    "livestock": 10,
    "road": 11}
tile_enum_to_type = {v:k for k,v in tile_type_to_enum.items()}

#t= df["tile"]

import json
#t_arr = json.loads('t')

def nutritionToDescription(nutritionValue):
    if nutritionValue < 3:
        return "low"
    elif nutritionValue < 24:
        return "medium"
    else: 
        return "high"

def progressToDescription(progressValue):
    if progressValue < 64:
        return "starting"
    elif nutritionValue < 191:
        return "in progress"
    else: 
        return "almost done"

#outputs: progress at [0], high/med/low nutrition, was og_type now my_type, position at x,y
def tile_myfunc(tile_json):
  if type(tile_json) != str and math.isnan(tile_json):
      return None
  tile_array = json.loads(tile_json)
  return convertTileArray(tile_array)

def convertTileArray(tile_array):
  val255 = tile_array[0]
  nutrition255 = tile_array[1]
  og_type, my_type = tile_array[2], tile_array[3]
  tx,ty = tile_array[4],tile_array[5]

  progress = "progress at {}".format(progressToDescription(val255))
  curr_nutrition = "{} nutrition".format(nutritionToDescription(nutrition255))
  history = "was {} and now {}".format(tile_enum_to_type[og_type], tile_enum_to_type[my_type])
  position = "position at ({},{})".format(tx,ty)
  
  return progress, curr_nutrition, history, position


df['tile'] = df['tile'].map(tile_myfunc)

In [ ]:
#Farmbit Change

def valueToDescription(Value):
    if Value < 64:
        return "not"
    elif Value < 191:
        return "somewhat"
    else: 
        return "very"

#Names
whois_enum_to_name = {
    0: 'Peter',	
    1: 'Paul',
    2: 'Mary',
    3: 'John',
    4: 'George',
    5:	'Ringo'	,
    6:	'Yoko'	,
    7:	'Stevie',	
    8:	'Saanvi',	
    9:	'Nethra',	
    10:	'Meha',	
    11:	'Sidney',	
    12:	'Lucy',
    13:	'Belden',	
    14:	'Henry'	,
    15:	'Alejandro',	
    16:	'Victor',	
    17:'Richard'}

#fb state
fb_state_to_enum = {
    "null": '0',
    "dire": '1',
    "desperate": '2',
    "motivated": '3'}
fb_enum_to_state = {v:k for k,v in fb_state_to_enum.items()}


#Job_State to enum conversion
job_state_to_enum = {
    "null": 0,
    "get": 1,
    "seek": 2,
    "act": 3,}
job_enum_to_state = {v:k for k,v in job_state_to_enum.items()}

#enum to Job_Type
job_type_to_enum = {'null':0, 'idle':1, "wait":2, "eat":3, "sleep":4, 'play':5, 'plant' : 6, 'harvest':7, 'feed':8, 'fertilize':9, 'milk':10, 'export':11}
job_enum_to_type = {v:k for k,v in job_type_to_enum.items()}


import json

#outputs: who, where, job, personal stats
def fb_myfunc(fb_json):
  if type(fb_json) != str:
      return None
 
  fb_array = json.loads(fb_json)
  tx,ty = fb_array[0],fb_array[1]
  name = fb_array[2]
  job_state, job_type = fb_array[3], fb_array[4]
  fullness,energy,joy,fulfillment = fb_array[5],fb_array[6],fb_array[7], fb_array[8]
  
  who = "{}".format(whois_enum_to_name[name]) 
  position = "at ({},{})".format(tx,ty)
  job = "I'm {} to {}.".format(job_enum_to_state[job_state], job_enum_to_type[job_type])
  state = "I'm feeling {} full {} energetic {} joyful {} fulfilled.".format(valueToDescription(fullness),valueToDescription(energy),valueToDescription(joy),valueToDescription(fulfillment))
  
  return who,position,job,state


df['farmbit']=df['farmbit'].map(fb_myfunc)

In [ ]:
df.tail(n=20)

,session_id,player_id,level,event_custom,event_data_complex,client_time,req_id,session_n,http_user_agent,tile_states,tile_nutritions,continue,audio,fullscreen,event_category,event_label,event_type,blurb_history,tile,marks,buy,cost,curr_money,success,raining,curr_selection_type,gametime,timestamp,buy_hovers,farmbit,achievement,emote_enum,item,cur_speed,prev_speed,manual,prev_mark,shop_open,to_state,selected_buy,grave,achievements_open,road_builds,progress,convo,games_played,speaker
1231545,19100522470362350,a004,1,4,"{""farmbit"": [18, 27, 0, 3, 1, 125, 136, 255, 1...",2019-12-11 21:42:13,19110315421337510,981,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Peter, at (18,27), I'm act to idle., I'm feel...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231546,19100522470362350,a004,1,24,"{""farmbit"": [20, 26, 0, 2, 1, 122, 131, 255, 1...",2019-12-11 21:42:17,19110315421710640,982,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Peter, at (20,26), I'm seek to idle., I'm fee...",NaN,Ive got my floatie on flamingo swim emoji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231547,19100522470362350,a004,1,24,"{""farmbit"": [21, 23, 0, 2, 1, 119, 128, 254, 1...",2019-12-11 21:42:19,19110315421932600,983,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Peter, at (21,23), I'm seek to idle., I'm fee...",NaN,Ive got my floatie on flamingo swim emoji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231548,19100522470362350,a004,1,16,"{""cur_speed"": 4, ""prev_speed"": 2, ""manual"": 1,...",2019-12-11 21:42:19,19110315421974370,984,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,fast x 16,play x 1,Changed by Player,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231549,19100522470362350,a004,1,24,"{""farmbit"": [21, 20, 0, 3, 1, 117, 125, 255, 1...",2019-12-11 21:42:19,19110315421974370,985,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Peter, at (21,20), I'm act to idle., I'm feel...",NaN,Ive got my floatie on flamingo swim emoji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231550,19100522470362350,a004,1,21,"{""event_custom"": 21}",2019-12-11 21:42:23,19110315422364896,986,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231551,19100522470362350,a004,1,24,"{""farmbit"": [29, 29, 0, 2, 1, 101, 103, 238, 8...",2019-12-11 21:42:23,19110315422426256,987,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Peter, at (29,29), I'm seek to idle., I'm fee...",NaN,Im hungry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231552,19100522470362350,a004,1,24,"{""farmbit"": [30, 21, 0, 3, 3, 255, 99, 234, 81...",2019-12-11 21:42:24,19110315422426256,988,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Peter, at (30,21), I'm act to eat., I'm feeli...",NaN,Yumface,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231553,19100522470362350,a004,1,24,"{""farmbit"": [23, 22, 0, 3, 4, 252, 96, 231, 78...",2019-12-11 21:42:24,19110315422880836,989,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Peter, at (23,22), I'm act to sleep., I'm fee...",NaN,Im tired sleepy face,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231554,19100522470362350,a004,1,16,"{""cur_speed"": 2, ""prev_speed"": 4, ""manual"": 1,...",2019-12-11 21:42:24,19110315422880836,990,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,play x 1,fast x 16,Changed by Player,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231555,19100522470362350,a004,1,24,"{""farmbit"": [27, 16, 7, 3, 1, 101, 184, 198, 9...",2019-12-11 21:42:28,19110315422880836,991,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Stevie, at (27,16), I'm act to idle., I'm fee...",NaN,Im hungry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231556,19100522470362350,a004,1,24,"{""farmbit"": [27, 17, 7, 3, 3, 255, 184, 198, 9...",2019-12-11 21:42:28,19110315422907150,992,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Stevie, at (27,17), I'm act to eat., I'm feel...",NaN,Yumface,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231557,19100522470362350,a004,1,24,"{""farmbit"": [20, 20, 0, 2, 1, 245, 245, 222, 6...",2019-12-11 21:42:29,19110315422907150,993,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Peter, at (20,20), I'm seek to idle., I'm fee...",NaN,Ive got my floatie on flamingo swim emoji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231558,19100522470362350,a004,1,24,"{""farmbit"": [20, 21, 0, 2, 1, 236, 232, 251, 5...",2019-12-11 21:42:38,19110315423894830,994,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Peter, at (20,21), I'm seek to idle., I'm fee...",NaN,Ive got my floatie on flamingo swim emoji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231559,19100522470362350,a004,1,24,"{""farmbit"": [19, 23, 0, 2, 1, 228, 221, 254, 4...",2019-12-11 21:42:45,19110315424545330,995,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Peter, at (19,23), I'm seek to idle., I'm fee...",NaN,Ive got my floatie on flamingo swim emoji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231560,19100522470362350,a004,1,24,"{""farmbit"": [20, 21, 0, 2, 1, 215, 203, 254, 2...",2019-12-11 21:42:57,19110315425738170,996,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Peter, at (20,21), I'm seek to idle., I'm fee...",NaN,Ive got my floatie on flamingo swim emoji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231561,19100522470362350,a004,1,24,"{""farmbit"": [22, 25, 7, 2, 4, 195, 100, 114, 1...",2019-12-11 21:43:23,19110315432350704,997,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Stevie, at (22,25), I'm seek to sleep., I'm f...",NaN,Ive got my floatie on flamingo swim emoji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231562,19100522470362350,a004,1,24,"{""farmbit"": [22, 22, 7, 3, 4, 193, 98, 253, 13...",2019-12-11 21:43:24,19110315432490216,998,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Stevie, at (22,22), I'm act to sleep., I'm fe...",NaN,Im tired sleepy face,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231563,19100522470362350,a004,1,16,"{""cur_speed"": 1, ""prev_speed"": 2, ""manual"": 1,...",2019-12-11 21:43:27,19110315432775064,999,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,pause,play x 1,Changed by Player,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game
1231564,19100522470362350,a004,1,13,"{""shop_open"": true, ""event_custom"": 13}",2019-12-12 18:45:10,19110412451075656,1000,Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,true,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,game

In [ ]:
#Items

#Item_Type to enum conversion
item_type_to_enum = {
    "null": 0,
    "water": 1,
    "food": 2,
    "poop": 3,
    "fertilizer": 4,
    "milk": 5}  
item_enum_to_type = {v:k for k,v in item_type_to_enum.items()}

#Item_Marks to Enum
mark_type_to_enum = {'null': 0,
    "use": 1,
    "sell": 2,
    "feed": 3}
mark_enum_to_type = {v:k for k,v in mark_type_to_enum.items()}


import json

#outputs: where, what, how
def item_myfunc(item_json):
  if type(item_json) != str:
      return None

  item_array = json.loads(item_json)
  tx,ty = item_array[0],item_array[1]
  item, mark = item_array[2], item_array[3]
  
  where = "at ({},{})".format(tx,ty) 
  what = "{} for {}".format((item_enum_to_type[item]),(mark_enum_to_type[mark]))
  
  return where,what

df['item']= df['item'].map(item_myfunc)

In [ ]:
#Marks

#Item_Marks to Enum
mark_type_to_enum = {'null': 0,
    "use": 1,
    "sell": 2,
    "feed": 3}

mark_enum_to_type = {v:k for k,v in mark_type_to_enum.items()}

#Marks outputs: item marks for item, tile, etc.
def mark_myfunc(mark_json):
  if type(mark_json) != str:
      return None

  mark_array = json.loads(mark_json)
  mark_1, mark_2 = mark_array[0],mark_array[1]
  mark_unused, mark_unused2 = mark_array[2], mark_array[3]

  desc_mark="Items marked for {} and {}.".format((mark_enum_to_type[mark_1]),(mark_enum_to_type[mark_2]))

  return desc_mark


df.marks = df['marks'].map(mark_myfunc)

In [ ]:
#Hovers

def buyHovers_func(json_str):
    if type(json_str) != str:
      return None
    
    buyHovers_arr = json.loads(json_str)
    return convertBuyHoversArray(buyHovers_arr)

def convertBuyHoversArray(buyHovers_arr):
    buyHoversDescriptionArray = []
    for tile_arr in buyHovers_arr:
        fullTileDescription = convertTileArrayForBuyHovers(tile_arr);
        buyHoversDescriptionArray.append(fullTileDescription)
    return buyHoversDescriptionArray



def convertTileArrayForBuyHovers(tile_array):
  val255 = tile_array[0]
  nutrition255 = tile_array[1]
  og_type, my_type = tile_array[2], tile_array[3]
  tx,ty = tile_array[4],tile_array[5]

  progress = "progress at {}".format(progressToDescription(val255))
  curr_nutrition = "{} nutrition".format(nutritionToDescription(nutrition255))
  history = "was {} and now {}".format(tile_enum_to_type[og_type], tile_enum_to_type[my_type])
  position = "position at ({},{})".format(tx,ty)
  
  return progress, curr_nutrition, history, position

df.buy_hovers = df.buy_hovers.map(buyHovers_func)

#Combine Descriptor Columns

In [ ]:
#Text Data Column

#For every description, add column name + description

if ('text_data' not in df):
  df['text_data'] = ''

columnsToCombine = ['event_category', 'event_label', 'continue', 'tile',
       'marks', 'farmbit', 'item', 'buy', 'cost', 'curr_money',
       'success', 'buy_hovers', 'selected_buy', 'prev_mark',
       'to_state', 'shop_open', 'achievements_open', 'cur_speed',
       'prev_speed', 'manual', 'achievement', 'emote_enum'];

for index, row in df.iterrows():
  if(df.loc[index, 'text_data'] == ''):
    textValue = ''
    for columnName in columnsToCombine:
      columnValue = df.loc[index, columnName]
      if columnValue != 'None' and columnValue != None:
        if textValue != '':
          textValue = textValue + ', '
        textValue = textValue + "{}: {}".format(columnName, columnValue)


    textValue = '{event_custom: ' + df.loc[index, 'event_custom'] + ', data:{' + textValue + '}}'
    
    df.loc[index, 'text_data'] = textValue

In [ ]:
df['text_data']

150197     {event_custom: 1, data:{event_category: nan, e...
150198     {event_custom: 2, data:{event_category: "begin...
150199     {event_custom: 3, data:{event_category: nan, e...
150200     {event_custom: 3, data:{event_category: nan, e...
150201     {event_custom: 3, data:{event_category: nan, e...
                                 ...
1231560    {event_custom: 24, data:{event_category: nan, ...
1231561    {event_custom: 24, data:{event_category: nan, ...
1231562    {event_custom: 24, data:{event_category: nan, ...
1231563    {event_custom: 16, data:{event_category: nan, ...
1231564    {event_custom: 13, data:{event_category: nan, ...
Name: text_data, Length: 120025, dtype: object

#Add Meta Data

1.   Add Conversation Markers - Continue = 2, etc
2.   Add Game vs. Player label

#Save To CSV

In [ ]:
split_list = dict(tuple(df.groupby('session_id')))
for session in split_list.keys():
    split_list[session].to_csv(f"/content/drive/My Drive/Research/2021_JLA_GameDataQE/Testing/{session}.csv", index=False)

In [ ]:
df.describe

<bound method NDFrame.describe of                 session_id player_id  level event_custom  \
150197   19100107575255310      a017      1            1
150198   19100107575255310      a017      1            2
150199   19100107575255310      a017      1            3
150200   19100107575255310      a017      1            3
150201   19100107575255310      a017      1            3
...                    ...       ...    ...          ...
1231560  19100522470362350      a004      1           24
1231561  19100522470362350      a004      1           24
1231562  19100522470362350      a004      1           24
1231563  19100522470362350      a004      1           16
1231564  19100522470362350      a004      1           13

                                        event_data_complex  \
150197   {"tile_states": [3, 3, 3, 3, 3, 3, 3, 3, 3, 4,...
150198   {"event_category": "begin", "event_label": "bu...
150199   {"tile": [0, 12, 1, 1, 25, 19], "marks": [1, 1...
150200   {"tile": [0, 8, 6, 6, 23, 25], "marks": [1, 1,...
150201   {"tile": [0, 12, 1, 1, 21, 19], "marks": [1, 1...
...                                                    ...
1231560  {"farmbit": [20, 21, 0, 2, 1, 215, 203, 254, 2...
1231561  {"farmbit": [22, 25, 7, 2, 4, 195, 100, 114, 1...
1231562  {"farmbit": [22, 22, 7, 3, 4, 193, 98, 253, 13...
1231563  {"cur_speed": 1, "prev_speed": 2, "manual": 1,...
1231564            {"shop_open": true, "event_custom": 13}

                 client_time             req_id  session_n  \
150197   2019-11-25 13:59:23  19100107592318700          0
150198         1574690374141  19100107593498740          1
150199   2019-11-25 13:59:43  19100107594375784          2
150200   2019-11-25 13:59:49  19100107594980116          3
150201   2019-11-25 13:59:52  19100107595287100          4
...                      ...                ...        ...
1231560  2019-12-11 21:42:57  19110315425738170        996
1231561  2019-12-11 21:43:23  19110315432350704        997
1231562  2019-12-11 21:43:24  19110315432490216        998
1231563  2019-12-11 21:43:27  19110315432775064        999
1231564  2019-12-12 18:45:10  19110412451075656       1000

                                           http_user_agent  \
150197   Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...
150198   Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...
150199   Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...
150200   Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...
150201   Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...
...                                                    ...
1231560  Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...
1231561  Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...
1231562  Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...
1231563  Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...
1231564  Mozilla/5.0 (X11; CrOS x86_64 12499.66.0) Appl...

                                               tile_states  \
150197   [3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 5, 3, ...
150198                                                 NaN
150199                                                 NaN
150200                                                 NaN
150201                                                 NaN
...                                                    ...
1231560                                                NaN
1231561                                                NaN
1231562                                                NaN
1231563                                                NaN
1231564                                                NaN

                                           tile_nutritions continue audio  \
150197   [0, 0, 1, 1, 12, 12, 12, 12, 12, 12, 12, 12, 1...        0     1
150198                                                 NaN      NaN   NaN
150199                                                 NaN      NaN   NaN
150200                                                 NaN      NaN   NaN
150201                                                 NaN      NaN   NaN
...                                                    ...      ...   ...
1231560                                                NaN      NaN   NaN
1231561                                                NaN      NaN   NaN
1231562                                                NaN      NaN   NaN
1231563                                                NaN      NaN   NaN
1231564                                                NaN      NaN   NaN

        fullscreen event_category      event_label  event_type blurb_history  \
150197           0            NaN              NaN         NaN           NaN
150198         NaN        "begin"  "build_a_house"  "tutorial"            []
150199         NaN            NaN              NaN         NaN           NaN
150200         NaN            NaN              NaN         NaN           NaN
150201         NaN            NaN              NaN         NaN           NaN
...            ...            ...              ...         ...           ...
1231560        NaN            NaN              NaN         NaN           NaN
1231561        NaN            NaN              NaN         NaN           NaN
1231562        NaN            NaN              NaN         NaN           NaN
1231563        NaN            NaN              NaN         NaN           NaN
1231564        NaN            NaN              NaN         NaN           NaN

                                                      tile  \
150197                                                None
150198                                                None
150199   (progress at starting, medium nutrition, was l...
150200   (progress at starting, medium nutrition, was s...
150201   (progress at starting, medium nutrition, was l...
...                                                    ...
1231560                                               None
1231561                                               None
1231562                                               None
1231563                                               None
1231564                                               None

                                 marks  buy cost curr_money success raining  \
150197                            None  NaN  NaN        NaN     NaN     NaN
150198                            None  NaN  NaN        NaN     NaN     NaN
150199   Items marked for use and use.  NaN  NaN        NaN     NaN     NaN
150200   Items marked for use and use.  NaN  NaN        NaN     NaN     NaN
150201   Items marked for use and use.  NaN  NaN        NaN     NaN     NaN
...                                ...  ...  ...        ...     ...     ...
1231560                           None  NaN  NaN        NaN     NaN     NaN
1231561                           None  NaN  NaN        NaN     NaN     NaN
1231562                           None  NaN  NaN        NaN     NaN     NaN
1231563                           None  NaN  NaN        NaN     NaN     NaN
1231564                           None  NaN  NaN        NaN     NaN     NaN

        curr_selection_type gametime timestamp buy_hovers  \
150197                  NaN      NaN       NaN       None
150198                  NaN      NaN       NaN       None
150199                  NaN      NaN       NaN       None
150200                  NaN      NaN       NaN       None
150201                  NaN      NaN       NaN       None
...                     ...      ...       ...        ...
1231560                 NaN      NaN       NaN       None
1231561                 NaN      NaN       NaN       None
1231562                 NaN      NaN       NaN       None
1231563                 NaN      NaN       NaN       None
1231564                 NaN      NaN       NaN       None

                                                   farmbit achievement  \
150197                                                None         NaN
150198                                                None         NaN
150199                                                None         NaN
150200                                                None         NaN
150201                                                None         NaN
...                                                    ...         ...
1231560  (Peter, at (20,21), I'm seek to idle., I'm fee...         NaN
1231561  (Stevie, at (22,25), I'm seek to sleep., I'm f...         NaN
1231562  (Stevie, at (22,22), I'm act to sleep., I'm fe...         NaN
1231563                                               None         NaN
1231564                                               None         NaN

                                        emote_enum  item cur_speed prev_speed  \
150197                                         NaN  None       NaN        NaN
150198                                         NaN  None       NaN        NaN
150199                                         NaN  None       NaN        NaN
150200                                         NaN  None       NaN        NaN
150201                                         NaN  None       NaN        NaN
...                                            ...   ...       ...        ...
1231560  Ive got my floatie on flamingo swim emoji  None       NaN        NaN
1231561  Ive got my floatie on flamingo swim emoji  None       NaN        NaN
1231562                       Im tired sleepy face  None       NaN        NaN
1231563                                        NaN  None     pause   play x 1
1231564                                        NaN  None       NaN        NaN

                    manual prev_mark shop_open to_state selected_buy grave  \
150197                 NaN       NaN       NaN      NaN          NaN   NaN
150198                 NaN       NaN       NaN      NaN          NaN   NaN
150199                 NaN       NaN       NaN      NaN          NaN   NaN
150200                 NaN       NaN       NaN      NaN          NaN   NaN
150201                 NaN       NaN       NaN      NaN          NaN   NaN
...                    ...       ...       ...      ...          ...   ...
1231560                NaN       NaN       NaN      NaN          NaN   NaN
1231561                NaN       NaN       NaN      NaN          NaN   NaN
1231562                NaN       NaN       NaN      NaN          NaN   NaN
1231563  Changed by Player       NaN       NaN      NaN          NaN   NaN
1231564                NaN       NaN      true      NaN          NaN   NaN

        achievements_open road_builds  progress  convo  games_played speaker  \
150197                NaN         NaN       1.0    1.0           1.0    game
150198                NaN         NaN       1.0    1.0           1.0    game
150199                NaN         NaN       1.0    1.0           1.0    game
150200                NaN         NaN       1.0    1.0           1.0    game
150201                NaN         NaN       1.0    1.0           1.0    game
...                   ...         ...       ...    ...           ...     ...
1231560               NaN         NaN       1.0    1.0           1.0    game
1231561               NaN         NaN       1.0    1.0           1.0    game
1231562               NaN         NaN       1.0    1.0           1.0    game
1231563               NaN         NaN       1.0    1.0           1.0    game
1231564               NaN         NaN       1.0    1.0           1.0    game

                                                 text_data
150197   {event_custom: 1, data:{event_category: nan, e...
150198   {event_custom: 2, data:{event_category: "begin...
150199   {event_custom: 3, data:{event_category: nan, e...
150200   {event_custom: 3, data:{event_category: nan, e...
150201   {event_custom: 3, data:{event_category: nan, e...
...                                                    ...
1231560  {event_custom: 24, data:{event_category: nan, ...
1231561  {event_custom: 24, data:{event_category: nan, ...
1231562  {event_custom: 24, data:{event_category: nan, ...
1231563  {event_custom: 16, data:{event_category: nan, ...
1231564  {event_custom: 13, data:{event_category: nan, ...

[120025 rows x 48 columns]>